// This file is generated by GoAdmin CLI adm.
package adm

import (
	"github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"
)

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "refresh_tokens" => http://localhost:9033/admin/info/refresh_tokens
// "kyc_results" => http://localhost:9033/admin/info/kyc_results
// "notifications_gateway_app_notification_recipients" => http://localhost:9033/admin/info/notifications_gateway_app_notification_recipients
// "license" => http://localhost:9033/admin/info/license
// "counterparty_accounts" => http://localhost:9033/admin/info/counterparty_accounts
// "company_info" => http://localhost:9033/admin/info/company_info
// "counterparty" => http://localhost:9033/admin/info/counterparty
// "users" => http://localhost:9033/admin/info/users
// "invitations" => http://localhost:9033/admin/info/invitations
// "base_profile" => http://localhost:9033/admin/info/base_profile
// "profile" => http://localhost:9033/admin/info/profile
// "devices" => http://localhost:9033/admin/info/devices
// "swaggers" => http://localhost:9033/admin/info/swaggers
// "projects" => http://localhost:9033/admin/info/projects
// "roles" => http://localhost:9033/admin/info/roles
// "action_groups" => http://localhost:9033/admin/info/action_groups
// "actions" => http://localhost:9033/admin/info/actions
// "roles_actions" => http://localhost:9033/admin/info/roles_actions
// "notifications_gateway_app_notification_statuses" => http://localhost:9033/admin/info/notifications_gateway_app_notification_statuses
// "notification" => http://localhost:9033/admin/info/notification
// "loan_agreements" => http://localhost:9033/admin/info/loan_agreements
// "schema_migrations" => http://localhost:9033/admin/info/schema_migrations
// "payments" => http://localhost:9033/admin/info/payments
// "payment_employees" => http://localhost:9033/admin/info/payment_employees
// "profiles" => http://localhost:9033/admin/info/profiles
// "notification_center" => http://localhost:9033/admin/info/notification_center
// "otps" => http://localhost:9033/admin/info/otps
// "biometry_results" => http://localhost:9033/admin/info/biometry_results
// "payment_taxes" => http://localhost:9033/admin/info/payment_taxes
//
// example end
var Generators = map[string]table.Generator{
	"refresh_tokens": GetRefreshtokensTable,
	"kyc_results":    GetKycresultsTable,
	"notifications_gateway_app_notification_recipients": GetNotificationsgatewayappnotificationrecipientsTable,
	"license":               GetLicenseTable,
	"counterparty_accounts": GetCounterpartyaccountsTable,
	"company_info":          GetCompanyinfoTable,
	"counterparty":          GetCounterpartyTable,
	"users":                 GetUsersTable,
	"invitations":           GetInvitationsTable,
	"base_profile":          GetBaseprofileTable,
	"profile":               GetProfileTable,
	"devices":               GetDevicesTable,
	"swaggers":              GetSwaggersTable,
	"projects":              GetProjectsTable,
	"roles":                 GetRolesTable,
	"action_groups":         GetActiongroupsTable,
	"actions":               GetActionsTable,
	"roles_actions":         GetRolesactionsTable,
	"notifications_gateway_app_notification_statuses": GetNotificationsgatewayappnotificationstatusesTable,
	"notification":        GetNotificationTable,
	"loan_agreements":     GetLoanagreementsTable,
	"schema_migrations":   GetSchemamigrationsTable,
	"payments":            GetPaymentsTable,
	"payment_employees":   GetPaymentemployeesTable,
	"profiles":            GetProfilesTable,
	"notification_center": GetNotificationcenterTable,
	"otps":                GetOtpsTable,
	"biometry_results":    GetBiometryresultsTable,
	"payment_taxes":       GetPaymenttaxesTable,

	// generators end
}
